#!/bin/sh -e

set -x

# Sync Python environment
uv sync --all-extras --frozen

# Install Client dependencies
cd pywire/src/pywire/client && pnpm install
cd -

# Install Docs dependencies
cd docs && pnpm install
cd -