/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 1
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__directive_single_line_token1 = 1,
  aux_sym__directive_single_line_token2 = 2,
  sym__directive_content = 3,
  anon_sym_BANGpath = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  aux_sym__directive_multiline_content_token1 = 7,
  sym__python_block = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_LT_SLASH = 11,
  aux_sym_tag_name_token1 = 12,
  anon_sym_EQ = 13,
  aux_sym__attribute_name_token1 = 14,
  aux_sym__attribute_name_token2 = 15,
  aux_sym__attribute_name_token3 = 16,
  anon_sym_DQUOTE = 17,
  aux_sym_attribute_value_token1 = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_attribute_value_token2 = 20,
  sym_separator = 21,
  sym_text = 22,
  sym_hyphen = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym_directive = 26,
  sym__directive_single_line = 27,
  sym__directive_multiline = 28,
  sym__directive_multiline_content = 29,
  sym_python_section = 30,
  sym__html_content = 31,
  sym_tag = 32,
  sym_tag_name = 33,
  sym_attribute = 34,
  sym__attribute_name = 35,
  sym_attribute_value = 36,
  sym_interpolation = 37,
  sym__interpolation_content = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym__directive_multiline_repeat1 = 40,
  aux_sym_tag_repeat1 = 41,
  aux_sym_tag_repeat2 = 42,
  alias_sym_attribute_name = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__directive_single_line_token1] = "keyword_directive",
  [aux_sym__directive_single_line_token2] = "_directive_single_line_token2",
  [sym__directive_content] = "_directive_content",
  [anon_sym_BANGpath] = "keyword_directive",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__directive_multiline_content_token1] = "_directive_multiline_content_token1",
  [sym__python_block] = "python_code",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_EQ] = "=",
  [aux_sym__attribute_name_token1] = "special_attribute_name",
  [aux_sym__attribute_name_token2] = "special_attribute_name",
  [aux_sym__attribute_name_token3] = "special_attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_attribute_value_token1] = "attribute_content",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_value_token2] = "attribute_content",
  [sym_separator] = "separator",
  [sym_text] = "text",
  [sym_hyphen] = "hyphen",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_directive] = "directive",
  [sym__directive_single_line] = "_directive_single_line",
  [sym__directive_multiline] = "_directive_multiline",
  [sym__directive_multiline_content] = "python_code",
  [sym_python_section] = "python_section",
  [sym__html_content] = "_html_content",
  [sym_tag] = "tag",
  [sym_tag_name] = "tag_name",
  [sym_attribute] = "attribute",
  [sym__attribute_name] = "_attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_interpolation] = "interpolation",
  [sym__interpolation_content] = "python_code",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__directive_multiline_repeat1] = "_directive_multiline_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_tag_repeat2] = "tag_repeat2",
  [alias_sym_attribute_name] = "attribute_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__directive_single_line_token1] = aux_sym__directive_single_line_token1,
  [aux_sym__directive_single_line_token2] = aux_sym__directive_single_line_token2,
  [sym__directive_content] = sym__directive_content,
  [anon_sym_BANGpath] = aux_sym__directive_single_line_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__directive_multiline_content_token1] = aux_sym__directive_multiline_content_token1,
  [sym__python_block] = sym__python_block,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym__attribute_name_token1] = aux_sym__attribute_name_token1,
  [aux_sym__attribute_name_token2] = aux_sym__attribute_name_token1,
  [aux_sym__attribute_name_token3] = aux_sym__attribute_name_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_value_token2] = aux_sym_attribute_value_token1,
  [sym_separator] = sym_separator,
  [sym_text] = sym_text,
  [sym_hyphen] = sym_hyphen,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_directive] = sym_directive,
  [sym__directive_single_line] = sym__directive_single_line,
  [sym__directive_multiline] = sym__directive_multiline,
  [sym__directive_multiline_content] = sym__python_block,
  [sym_python_section] = sym_python_section,
  [sym__html_content] = sym__html_content,
  [sym_tag] = sym_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_attribute] = sym_attribute,
  [sym__attribute_name] = sym__attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_interpolation] = sym_interpolation,
  [sym__interpolation_content] = sym__python_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__directive_multiline_repeat1] = aux_sym__directive_multiline_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_tag_repeat2] = aux_sym_tag_repeat2,
  [alias_sym_attribute_name] = alias_sym_attribute_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__directive_single_line_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__directive_single_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__directive_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANGpath] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__directive_multiline_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__python_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__attribute_name_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__attribute_name_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__attribute_name_token3] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_hyphen] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__directive_single_line] = {
    .visible = false,
    .named = true,
  },
  [sym__directive_multiline] = {
    .visible = false,
    .named = true,
  },
  [sym__directive_multiline_content] = {
    .visible = true,
    .named = true,
  },
  [sym_python_section] = {
    .visible = true,
    .named = true,
  },
  [sym__html_content] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_name] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__directive_multiline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_attribute_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 5,
  [11] = 9,
  [12] = 4,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 14,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 15,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 24,
  [36] = 36,
  [37] = 19,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 44,
  [50] = 43,
  [51] = 42,
  [52] = 48,
  [53] = 47,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 59,
  [64] = 57,
  [65] = 65,
  [66] = 66,
  [67] = 55,
  [68] = 68,
  [69] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '!', 12,
        '"', 78,
        '$', 13,
        '\'', 88,
        '-', 104,
        ':', 14,
        '<', 70,
        '=', 74,
        '>', 71,
        '@', 15,
        '{', 41,
        '}', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '<') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '<') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(98);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(103);
      if (lookahead == '<') ADVANCE(70);
      if (lookahead == '{') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '}') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(105);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 13:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(9);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      if (lookahead == '!') ADVANCE(100);
      if (lookahead == '-') ADVANCE(104);
      if (lookahead == '<') ADVANCE(69);
      if (lookahead == '{') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '!') ADVANCE(64);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '{') ADVANCE(68);
      if (lookahead == '}') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 'a') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 'a') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 'h') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 'h') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 't') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 't') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token2);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token2);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '<') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '!') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '>') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANGpath);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANGpath);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '!') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(51);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '<') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '!') ADVANCE(64);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '{') ADVANCE(68);
      if (lookahead == '}') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '!') ADVANCE(60);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(68);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(68);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(55);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(56);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(58);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '>') ADVANCE(68);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 'a') ADVANCE(65);
      if (lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 'h') ADVANCE(66);
      if (lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 'p') ADVANCE(62);
      if (lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(8);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '/') ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__attribute_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__attribute_name_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__attribute_name_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '!') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '-') ADVANCE(87);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '<') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '>') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '!') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '-') ADVANCE(97);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '-') ADVANCE(93);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '<') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '>') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(100);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'p') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_hyphen);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_hyphen);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 17},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 10},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 85},
  [66] = {.lex_state = 95},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__directive_single_line_token1] = ACTIONS(1),
    [anon_sym_BANGpath] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym__attribute_name_token1] = ACTIONS(1),
    [aux_sym__attribute_name_token2] = ACTIONS(1),
    [aux_sym__attribute_name_token3] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_hyphen] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_directive] = STATE(2),
    [sym__directive_single_line] = STATE(20),
    [sym__directive_multiline] = STATE(20),
    [sym_python_section] = STATE(2),
    [sym__html_content] = STATE(2),
    [sym_tag] = STATE(2),
    [sym_interpolation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym__directive_single_line_token1] = ACTIONS(7),
    [anon_sym_BANGpath] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [sym_separator] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
    [sym_hyphen] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      aux_sym__directive_single_line_token1,
    ACTIONS(9), 1,
      anon_sym_BANGpath,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      sym_separator,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 2,
      sym_text,
      sym_hyphen,
    STATE(20), 2,
      sym__directive_single_line,
      sym__directive_multiline,
    STATE(3), 6,
      sym_directive,
      sym_python_section,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [38] = 10,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym__directive_single_line_token1,
    ACTIONS(30), 1,
      anon_sym_BANGpath,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      anon_sym_LT,
    ACTIONS(39), 1,
      sym_separator,
    ACTIONS(42), 2,
      sym_text,
      sym_hyphen,
    STATE(20), 2,
      sym__directive_single_line,
      sym__directive_multiline,
    STATE(3), 6,
      sym_directive,
      sym_python_section,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [76] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LT_SLASH,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    STATE(8), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [101] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(57), 1,
      sym_text,
    ACTIONS(59), 1,
      sym_hyphen,
    STATE(4), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [126] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LT_SLASH,
    ACTIONS(61), 1,
      sym_text,
    ACTIONS(63), 1,
      sym_hyphen,
    STATE(9), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [151] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_text,
    ACTIONS(69), 1,
      sym_hyphen,
    STATE(11), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [176] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    ACTIONS(79), 1,
      sym_text,
    ACTIONS(82), 1,
      sym_hyphen,
    STATE(8), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [201] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    ACTIONS(85), 1,
      anon_sym_LT_SLASH,
    STATE(8), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [226] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_LT_SLASH,
    ACTIONS(89), 1,
      sym_text,
    ACTIONS(91), 1,
      sym_hyphen,
    STATE(12), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [251] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    ACTIONS(93), 1,
      anon_sym_LT_SLASH,
    STATE(8), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [276] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    STATE(8), 4,
      sym__html_content,
      sym_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [301] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 1,
      sym__python_block,
    ACTIONS(97), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [320] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_GT,
    ACTIONS(103), 1,
      aux_sym_tag_name_token1,
    STATE(29), 1,
      sym__attribute_name,
    STATE(26), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(105), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [342] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      aux_sym_tag_name_token1,
    ACTIONS(107), 1,
      anon_sym_GT,
    STATE(29), 1,
      sym__attribute_name,
    STATE(21), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(105), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [364] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [380] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [396] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [412] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [428] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [444] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      aux_sym_tag_name_token1,
    ACTIONS(129), 1,
      anon_sym_GT,
    STATE(29), 1,
      sym__attribute_name,
    STATE(26), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(105), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [466] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [482] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [498] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [514] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [530] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_GT,
    ACTIONS(149), 1,
      aux_sym_tag_name_token1,
    STATE(29), 1,
      sym__attribute_name,
    STATE(26), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(152), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [552] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [568] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      aux_sym_tag_name_token1,
    ACTIONS(159), 1,
      anon_sym_GT,
    STATE(29), 1,
      sym__attribute_name,
    STATE(14), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(105), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_EQ,
    ACTIONS(161), 5,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 6,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_EQ,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [616] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_text,
    ACTIONS(145), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [629] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 5,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 5,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [651] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_text,
    ACTIONS(157), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [664] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_text,
    ACTIONS(141), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 5,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [688] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_text,
    ACTIONS(123), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [701] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    ACTIONS(175), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(38), 2,
      sym__directive_multiline_content,
      aux_sym__directive_multiline_repeat1,
  [715] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(40), 2,
      sym__directive_multiline_content,
      aux_sym__directive_multiline_repeat1,
  [729] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(180), 1,
      aux_sym__directive_multiline_content_token1,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym__directive_multiline_content,
      aux_sym__directive_multiline_repeat1,
  [743] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_attribute_value,
  [756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(55), 1,
      sym_tag_name,
  [766] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(61), 1,
      sym_tag_name,
  [776] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(57), 1,
      sym_tag_name,
  [786] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(190), 2,
      anon_sym_RBRACE,
      aux_sym__directive_multiline_content_token1,
  [794] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(192), 1,
      aux_sym__directive_single_line_token2,
    ACTIONS(194), 1,
      sym__directive_content,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(15), 1,
      sym_tag_name,
  [814] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(196), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(63), 1,
      sym__interpolation_content,
  [824] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(64), 1,
      sym_tag_name,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(69), 1,
      sym_tag_name,
  [844] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(67), 1,
      sym_tag_name,
  [854] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(196), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(59), 1,
      sym__interpolation_content,
  [864] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_tag_name_token1,
    STATE(28), 1,
      sym_tag_name,
  [874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_SQUOTE,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_GT,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_GT,
  [902] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_GT,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_GT,
  [951] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(218), 1,
      aux_sym_attribute_value_token1,
  [958] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(220), 1,
      aux_sym_attribute_value_token2,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_GT,
  [972] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(224), 1,
      aux_sym__directive_single_line_token2,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 101,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 201,
  [SMALL_STATE(10)] = 226,
  [SMALL_STATE(11)] = 251,
  [SMALL_STATE(12)] = 276,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 320,
  [SMALL_STATE(15)] = 342,
  [SMALL_STATE(16)] = 364,
  [SMALL_STATE(17)] = 380,
  [SMALL_STATE(18)] = 396,
  [SMALL_STATE(19)] = 412,
  [SMALL_STATE(20)] = 428,
  [SMALL_STATE(21)] = 444,
  [SMALL_STATE(22)] = 466,
  [SMALL_STATE(23)] = 482,
  [SMALL_STATE(24)] = 498,
  [SMALL_STATE(25)] = 514,
  [SMALL_STATE(26)] = 530,
  [SMALL_STATE(27)] = 552,
  [SMALL_STATE(28)] = 568,
  [SMALL_STATE(29)] = 590,
  [SMALL_STATE(30)] = 604,
  [SMALL_STATE(31)] = 616,
  [SMALL_STATE(32)] = 629,
  [SMALL_STATE(33)] = 640,
  [SMALL_STATE(34)] = 651,
  [SMALL_STATE(35)] = 664,
  [SMALL_STATE(36)] = 677,
  [SMALL_STATE(37)] = 688,
  [SMALL_STATE(38)] = 701,
  [SMALL_STATE(39)] = 715,
  [SMALL_STATE(40)] = 729,
  [SMALL_STATE(41)] = 743,
  [SMALL_STATE(42)] = 756,
  [SMALL_STATE(43)] = 766,
  [SMALL_STATE(44)] = 776,
  [SMALL_STATE(45)] = 786,
  [SMALL_STATE(46)] = 794,
  [SMALL_STATE(47)] = 804,
  [SMALL_STATE(48)] = 814,
  [SMALL_STATE(49)] = 824,
  [SMALL_STATE(50)] = 834,
  [SMALL_STATE(51)] = 844,
  [SMALL_STATE(52)] = 854,
  [SMALL_STATE(53)] = 864,
  [SMALL_STATE(54)] = 874,
  [SMALL_STATE(55)] = 881,
  [SMALL_STATE(56)] = 888,
  [SMALL_STATE(57)] = 895,
  [SMALL_STATE(58)] = 902,
  [SMALL_STATE(59)] = 909,
  [SMALL_STATE(60)] = 916,
  [SMALL_STATE(61)] = 923,
  [SMALL_STATE(62)] = 930,
  [SMALL_STATE(63)] = 937,
  [SMALL_STATE(64)] = 944,
  [SMALL_STATE(65)] = 951,
  [SMALL_STATE(66)] = 958,
  [SMALL_STATE(67)] = 965,
  [SMALL_STATE(68)] = 972,
  [SMALL_STATE(69)] = 979,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(48),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(53),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_section, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_section, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_single_line, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_single_line, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_multiline, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_multiline, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_single_line, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_single_line, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_multiline, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_multiline, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 8, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 8, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__attribute_name, 1, 0, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__directive_multiline_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__directive_multiline_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_multiline_content, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__interpolation_content, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [208] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pyhtml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
